### ISSUE TITLE
python error when adding second card

### ISSUE THREAD

**Issue by MX795** [Timtam/cards-against-humanity#1]
Run-Log:

C:\Python\Python27\python.exe E:/GitHub/cards-against-humanity/editor.py
Traceback (most recent call last):
  File "E:\GitHub\cards-against-humanity\editor\cardlist_toolbar.py", line 47, in newCard
    panel = frame.left_window.card_grid.addCard(id=cursor.lastrowid, text='', card_type=CARD_WHITE)
  File "E:\GitHub\cards-against-humanity\editor\cardlist.py", line 134, in addCard
    self.grid.Add(card, 1, wx.EXPAND | wx.ALL,
  File "C:\Python\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16711, in __getattr__
    raise PyDeadObjectError(self.attrStr % self._name)
wx._core.PyDeadObjectError: The C++ part of the GridSizer object has been deleted, attribute access no longer allowed.

**Comment by MX795** [comment]
additional info:
when you add just 1 card, it works fine, no matter if cards.db is empty or filled. with only 1 added card the editor doesn't crash on closing. when you add a second card, the above error shows up and it crashes on closing.

**Comment by MX795** [comment]
**fixed**

but need to check the graphics
